[application]
name = "psmf-dx"
default_platform = "fullstack"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "PSMF Mobile"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
index_on_404 = true

[web.resource.dev]
script = []